name: Test Publish

on:
  push:
    branches:
      - TMEDIA-569-publish-tags

jobs:
  publish:
    name: test build publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache NPM files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      # Sets up Node v12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Clean install dependencies if lockfile changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config with NPM token
        run: git config --global user.email "jack.howard@washpost.com" && git config --global user.name "jackhowa"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PERSONAL_AUTH_TOKEN }}

      - name: Get current datetime for re-running publish if necessary
        id: get-datetime
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Prerelease with tag, eg (`0.0.2-test.{hash of commit}.{current-date-time}`)
        run: npm version prerelease --preid=test.$(git rev-parse --short HEAD).${{ steps.get-datetime.outputs.date }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish with the tag test specified 
        run: npm publish --tag test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag of test
        run: git push origin TMEDIA-569-publish-tags -f
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}